class Signal:
    """
    Represents a trading signal generated by a Strategy.

    Attributes:
        type (str): "BUY" or "SELL".
        symbol (str): The asset symbol.
    """
    def __init__(self, type: str, symbol: str):
        self.type = type
        self.symbol = symbol

    def __str__(self):
        return f"Signal(type={self.type}, symbol={self.symbol})"