class Signal:
    """
    Represents a trading signal generated by a Strategy.

    Attributes:
        type (str): "BUY" or "SELL".
        symbol (str): The asset symbol.
        entry_price (float): The suggested entry price.
        quantity (float, optional): The suggested quantity to trade.
    """

    def __init__(self, type: str, symbol: str, entry_price: float, quantity: float = None):
        self.type = type
        self.symbol = symbol
        self.entry_price = entry_price
        self.quantity = quantity

    def __str__(self):
        return f"Signal(type={self.type}, symbol={self.symbol}, entry_price={self.entry_price}, quantity={self.quantity})"
